[package]
name = "gerber_parser"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
gerber-types = "0.2.0"

[dev-dependencies]
stringreader = "0.1.1"